---
- name: Create network
  openstack.cloud.network:
     cloud: "{{ cloud }}"
     name: "{{ network_name }}"
     state: present
     shared: "{{ network_shared }}"
     external: "{{ network_external }}"

- name: Gather networks info
  openstack.cloud.networks_info:
     cloud: "{{ cloud }}"
     name: "{{ network_name }}"
     filters:
       shared: "{{ network_shared|string|capitalize }}"
  register: result

- name: Verify networks info
  assert:
    that:
      - "result.openstack_networks.0.name ==  network_name"
      - "(result.openstack_networks.0.shared|lower) == (network_shared|lower)"
      - "result.openstack_networks[0]['router:external'] == {{ network_external }}"

- name: Delete network
  openstack.cloud.network:
     cloud: "{{ cloud }}"
     name: "{{ network_name }}"
     state: absent
