---
- name: Create network
  openstack.cloud.network:
     cloud: "{{ cloud }}"
     name: "{{ network_name }}"
     state: present
     shared: "{{ network_shared }}"
     external: "{{ network_external }}"

- name: Delete network
  openstack.cloud.network:
     cloud: "{{ cloud }}"
     name: "{{ network_name }}"
     state: absent
