# yamllint disable
---
- job:
    name: ansible-collections-openstack-functional-devstack
    parent: openstacksdk-functional-devstack
    description: |
      Run openstack collections functional tests against a master devstack
      using master of openstacksdk with latest ansible release
    required-projects:
      - openstack/ansible-collections-openstack
      - openstack/designate
    vars:
      zuul_work_dir: src/opendev.org/openstack/ansible-collections-openstack
      tox_envlist: ansible
      tox_install_siblings: true
      fetch_subunit: false
      devstack_plugins:
        designate: https://opendev.org/openstack/designate
      devstack_services:
        designate: true

- job:
    name: ansible-collections-openstack-functional-devstack-octavia
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a master devstack
      with Octavia plugin enabled, using releases of openstacksdk and latest
      ansible release. Run it only on Load Balancer changes.
    pre-run: ci/playbooks/get_amphora_tarball.yaml
    required-projects:
      - openstack/octavia
      - name: github.com/ansible/ansible
        override-checkout: stable-2.10
    files:
      - ^ci/roles/loadbalancer/.*$
      - ^plugins/modules/lb_health_monitor.py
      - ^plugins/modules/lb_listener.py
      - ^plugins/modules/lb_member.py
      - ^plugins/modules/lb_pool.py
      - ^plugins/modules/loadbalancer.py
    vars:
      tox_envlist: ansible
      devstack_plugins:
        designate: https://opendev.org/openstack/designate
        octavia: https://opendev.org/openstack/octavia
      devstack_services:
        designate: true
        octavia: true
        o-api: true
        o-cw: true
        o-hk: true
        o-hm: true
      devstack_localrc:
        OCTAVIA_AMP_IMAGE_FILE: "/tmp/test-only-amphora-x64-haproxy-ubuntu-bionic.qcow2"
        OCTAVIA_AMP_IMAGE_SIZE: 3
        OCTAVIA_AMP_IMAGE_NAME: "test-only-amphora-x64-haproxy-ubuntu-bionic"

- job:
    name: ansible-collections-openstack-functional-devstack-releases
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a master devstack
      using releases of openstacksdk and latest ansible release
    vars:
      tox_envlist: ansible
      tox_install_siblings: false

# Job with Ansible 2.9 for checking backward compatibility
- job:
    name: ansible-collections-openstack-functional-devstack-ansible-2.9
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a master devstack
      using master of openstacksdk and stable 2.9 branch of ansible
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.9
    vars:
      tox_envlist: ansible-2.9

- job:
    name: ansible-collections-openstack-functional-devstack-ansible-2.10
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a master devstack
      using master of openstacksdk and stable 2.10 branch of ansible
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.10
    vars:
      tox_envlist: ansible

- job:
    name: ansible-collections-openstack-functional-devstack-ansible-devel
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a master devstack
      using master of openstacksdk and devel branch of ansible
    voting: false
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: devel
    vars:
      tox_envlist: ansible-2.11

# Pip installation job
- job:
    name: ansible-collections-openstack-functional-devstack-ansible-pip
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a master devstack
      using master of openstacksdk with latest ansible release.
      Ansible collection is built using PIP.
    vars:
      tox_envlist: ansible-pip

# Stable branches tests
- job:
    name: ansible-collections-openstack-functional-devstack-victoria-ansible-2.10
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a victoria devstack
      using victoria brach of openstacksdk and stable 2.10 branch of ansible
    voting: true
    override-checkout: stable/victoria
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.10
      - name: openstack/openstacksdk
        override-checkout: stable/victoria
    vars:
      tox_envlist: ansible


- job:
    name: ansible-collections-openstack-functional-devstack-ussuri-ansible-2.10
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a ussuri devstack
      using ussuri brach of openstacksdk and stable 2.10 branch of ansible
    voting: true
    override-checkout: stable/ussuri
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.10
      - name: openstack/openstacksdk
        override-checkout: stable/ussuri
      - name: openstack/os-client-config
        override-checkout: stable/ussuri
    vars:
      tox_envlist: ansible

- job:
    name: ansible-collections-openstack-functional-devstack-train-ansible-2.10
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a train devstack
      using train brach of openstacksdk and stable 2.10 branch of ansible
    voting: false
    override-checkout: stable/train
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.10
      - name: openstack/openstacksdk
        override-checkout: stable/train
      - name: openstack/os-client-config
        override-checkout: stable/train
    vars:
      tox_envlist: ansible

- job:
    name: ansible-collections-openstack-functional-devstack-stein-ansible-2.10
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a stein devstack
      using stein brach of openstacksdk and stable 2.10 branch of ansible
    voting: true
    override-checkout: stable/stein
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.10
      - name: openstack/openstacksdk
        override-checkout: stable/stein
      - name: openstack/os-client-config
        override-checkout: stable/stein
    vars:
      tox_envlist: ansible

- job:
    name: ansible-collections-openstack-functional-devstack-rocky-ansible-2.10
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a rocky devstack
      using rocky brach of openstacksdk and stable 2.10 branch of ansible
    voting: true
    override-checkout: stable/rocky
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.10
      - name: openstack/openstacksdk
        override-checkout: stable/rocky
      - name: openstack/os-client-config
        override-checkout: stable/rocky
      - name: openstack/shade
        override-checkout: stable/rocky

    vars:
      tox_envlist: ansible

- job:
    name: ansible-collections-openstack-functional-devstack-queens-ansible-2.10
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a queens devstack
      using master branch of openstacksdk and stable 2.10 branch of ansible
    voting: true
    override-checkout: stable/queens
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.10
      - name: openstack/openstacksdk
        # Run queens with highest possible py2 version of SDK
        override-checkout: stable/train
    vars:
      tox_envlist: ansible

- job:
    name: ansible-collections-openstack-functional-devstack-queens-ansible-devel
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a queens devstack
      using master branch of openstacksdk and devel branch of ansible
    voting: false
    override-checkout: stable/queens
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: devel
      - name: openstack/openstacksdk
        # Run queens with highest possible py2 version of SDK
        override-checkout: stable/train
    vars:
      tox_envlist: ansible-2.11


# Linters
- job:
    name: openstack-tox-linters-ansible-devel
    parent: openstack-tox-linters
    nodeset: ubuntu-bionic
    description: |
      Run openstack collections linter tests using the devel branch of ansible
    # non-voting because we can't prevent ansible devel from breaking us
    voting: false
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: devel
    vars:
      tox_envlist: linters-2.11

- job:
    name: openstack-tox-linters-ansible-2.10
    parent: openstack-tox-linters
    nodeset: ubuntu-bionic
    description: |
      Run openstack collections linter tests using the 2.10 branch of ansible
    voting: true
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.10

- job:
    name: openstack-tox-linters-ansible-2.9
    parent: openstack-tox-linters
    nodeset: ubuntu-bionic
    description: |
      Run openstack collections linter tests using the 2.9 branch of ansible
    voting: true
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.9
    vars:
      tox_envlist: linters-2.9

# Cross-checks with other projects
- job:
    name: bifrost-collections-src
    parent: bifrost-integration-tinyipa-ubuntu-focal
    required-projects:
      - openstack/ansible-collections-openstack

- job:
    name: bifrost-keystone-collections-src
    parent: bifrost-integration-tinyipa-keystone-ubuntu-focal
    required-projects:
      - openstack/ansible-collections-openstack

- project:
    check:
      jobs:
        - tox-pep8
        - openstack-tox-linters-ansible-devel
        - openstack-tox-linters-ansible-2.10
        - openstack-tox-linters-ansible-2.9
        - ansible-collections-openstack-functional-devstack:
            dependencies: &deps_unit_lint
              - tox-pep8
              - openstack-tox-linters-ansible-2.9
              - openstack-tox-linters-ansible-2.10
            irrelevant-files: &ignore_files
              - changelogs/.*
              - COPYING
              - docs/.*
              - .*\.md
              - .*\.rst
              - tools/run-ansible-sanity.sh
              - tests/sanity/.*
              - contrib/.*

        - ansible-collections-openstack-functional-devstack-releases:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-ansible-2.9:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-ansible-2.10:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-ansible-devel:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-ansible-pip:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-victoria-ansible-2.10:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-ussuri-ansible-2.10:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-train-ansible-2.10:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-stein-ansible-2.10:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-rocky-ansible-2.10:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-queens-ansible-2.10:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-octavia:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files

        - bifrost-collections-src:
            voting: false
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - bifrost-keystone-collections-src:
            voting: false
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files

    gate:
      jobs:
        - tox-pep8
        - openstack-tox-linters-ansible-2.10
        - openstack-tox-linters-ansible-2.9
        - ansible-collections-openstack-functional-devstack
        - ansible-collections-openstack-functional-devstack-releases
        - ansible-collections-openstack-functional-devstack-ansible-2.9
        - ansible-collections-openstack-functional-devstack-ansible-2.10
        - ansible-collections-openstack-functional-devstack-ansible-pip
        - ansible-collections-openstack-functional-devstack-victoria-ansible-2.10
        - ansible-collections-openstack-functional-devstack-ussuri-ansible-2.10
        # - ansible-collections-openstack-functional-devstack-train-ansible-2.10
        - ansible-collections-openstack-functional-devstack-stein-ansible-2.10
        - ansible-collections-openstack-functional-devstack-rocky-ansible-2.10
        - ansible-collections-openstack-functional-devstack-queens-ansible-2.10
        - ansible-collections-openstack-functional-devstack-octavia

    periodic:
      jobs:
        - openstack-tox-linters-ansible-devel
        - openstack-tox-linters-ansible-2.10
        - openstack-tox-linters-ansible-2.9
        - ansible-collections-openstack-functional-devstack
        - ansible-collections-openstack-functional-devstack-releases
        - ansible-collections-openstack-functional-devstack-ansible-2.9
        - ansible-collections-openstack-functional-devstack-ansible-2.10
        - ansible-collections-openstack-functional-devstack-ansible-devel
        - ansible-collections-openstack-functional-devstack-ansible-pip
        - ansible-collections-openstack-functional-devstack-victoria-ansible-2.10
        - ansible-collections-openstack-functional-devstack-ussuri-ansible-2.10
        - ansible-collections-openstack-functional-devstack-train-ansible-2.10
        - ansible-collections-openstack-functional-devstack-stein-ansible-2.10
        - ansible-collections-openstack-functional-devstack-rocky-ansible-2.10
        - ansible-collections-openstack-functional-devstack-queens-ansible-2.10
        - ansible-collections-openstack-functional-devstack-queens-ansible-devel
        - bifrost-collections-src
        - bifrost-keystone-collections-src
        - ansible-collections-openstack-functional-devstack-octavia
