# yamllint disable
---
- job:
    name: ansible-collections-openstack-functional-devstack
    parent: openstacksdk-functional-devstack
    description: |
      Run openstack collections functional tests against a master devstack
      using master of openstacksdk with latest ansible release
    required-projects:
      - openstack/ansible-collections-openstack
    vars:
      zuul_work_dir: src/opendev.org/openstack/ansible-collections-openstack
      tox_envlist: ansible
      tox_install_siblings: true
      fetch_subunit: false

- job:
    name: ansible-collections-openstack-functional-devstack-releases
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a master devstack
      using releases of openstacksdk and latest ansible release
    vars:
      tox_install_siblings: false

- job:
    name: ansible-collections-openstack-functional-devstack-ansible-devel
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a master devstack
      using master of openstacksdk and devel branch of ansible
    # non-voting because we can't prevent ansible devel from breaking us
    voting: false
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: devel

- job:
    name: ansible-collections-openstack-functional-devstack-ansible-2.9
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a master devstack
      using master of openstacksdk and stable 2.9 branch of ansible
    voting: true
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.9

- job:
    name: ansible-collections-openstack-functional-devstack-train-ansible-devel
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a train devstack
      using train brach of openstacksdk and devel branch of ansible
    # non-voting because we can't prevent ansible devel from breaking us
    voting: false
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: devel
      - name: openstack/openstacksdk
        override-branch: train
      - name: openstack/devstack
        override-checkout: train

- job:
    name: ansible-collections-openstack-functional-devstack-train-ansible-2.9
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a train devstack
      using train brach of openstacksdk and stable 2.9 branch of ansible
    voting: true
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.9
      - name: openstack/openstacksdk
        override-branch: train
      - name: openstack/devstack
        override-checkout: train

- job:
    name: ansible-collections-openstack-functional-devstack-stein-ansible-devel
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a stein devstack
      using stein brach of openstacksdk and devel branch of ansible
    # non-voting because we can't prevent ansible devel from breaking us
    voting: false
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: devel
      - name: openstack/openstacksdk
        override-branch: stein
      - name: openstack/devstack
        override-checkout: stein

- job:
    name: ansible-collections-openstack-functional-devstack-stein-ansible-2.9
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a stein devstack
      using stein brach of openstacksdk and stable 2.9 branch of ansible
    voting: true
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.9
      - name: openstack/openstacksdk
        override-branch: stein
      - name: openstack/devstack
        override-checkout: stein

- job:
    name: ansible-collections-openstack-functional-devstack-rocky-ansible-devel
    parent: ansible-collections-openstack-functional-devstack
    description: |
      Run openstack collections functional tests against a rocky devstack
      using rocky brach of openstacksdk and devel branch of ansible
    # non-voting because we can't prevent ansible devel from breaking us
    voting: false
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: devel
      - name: openstack/openstacksdk
        override-branch: rocky
      - name: openstack/devstack
        override-checkout: rocky

- job:
    name: ansible-collections-openstack-functional-devstack-rocky-ansible-2.9
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a rocky devstack
      using rocky brach of openstacksdk and stable 2.9 branch of ansible
    voting: true
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.9
      - name: openstack/openstacksdk
        override-branch: rocky
      - name: openstack/devstack
        override-checkout: rocky

- job:
    name: ansible-collections-openstack-functional-devstack-queens-ansible-2.9
    parent: ansible-collections-openstack-functional-devstack-ansible-devel
    description: |
      Run openstack collections functional tests against a queens devstack
      using master brach of openstacksdk and stable 2.9 branch of ansible
    voting: true
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.9
      - name: openstack/openstacksdk
        override-branch: master
      - name: openstack/devstack
        override-checkout: queens

- job:
    name: openstack-tox-linters-ansible-devel
    parent: openstack-tox-linters
    description: |
      Run openstack collections linter tests using the devel branch of ansible
    # non-voting because we can't prevent ansible devel from breaking us
    voting: false
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: devel

- job:
    name: openstack-tox-linters-ansible-2.9
    parent: openstack-tox-linters
    description: |
      Run openstack collections linter tests using the 2.9 branch of ansible
    voting: true
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.9

- project:
    check:
      jobs:
        - tox-pep8
        - openstack-tox-linters-ansible-devel
        - openstack-tox-linters-ansible-2.9
        - ansible-collections-openstack-functional-devstack:
            dependencies: &deps_unit_lint
              - tox-pep8
              - openstack-tox-linters-ansible-2.9
            irrelevant-files: &ignore_files
              - changelogs/.*
              - COPYING
              - docs/.*
              - .*\.md
              - .*\.rst
              - tools/run-ansible-sanity.sh
              - tests/sanity/.*
              - contrib/.*

        - ansible-collections-openstack-functional-devstack-releases:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-ansible-devel:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-ansible-2.9:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-train-ansible-devel:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-train-ansible-2.9:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-stein-ansible-devel:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-stein-ansible-2.9:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-rocky-ansible-devel:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-rocky-ansible-2.9:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files
        - ansible-collections-openstack-functional-devstack-queens-ansible-2.9:
            dependencies: *deps_unit_lint
            irrelevant-files: *ignore_files


    gate:
      jobs:
        - tox-pep8
        - openstack-tox-linters
        - ansible-collections-openstack-functional-devstack
        - ansible-collections-openstack-functional-devstack-releases
        - ansible-collections-openstack-functional-devstack-ansible-2.9
        - ansible-collections-openstack-functional-devstack-train-ansible-2.9
        - ansible-collections-openstack-functional-devstack-stein-ansible-2.9
        - ansible-collections-openstack-functional-devstack-rocky-ansible-2.9
        - ansible-collections-openstack-functional-devstack-queens-ansible-2.9

