---
- name: Create volume
  openstack.cloud.volume:
     cloud: "{{ cloud }}"
     state: present
     size: 1
     display_name: ansible_volume
     display_description: Test volume
  register: vol

- name: Create volume backup
  openstack.cloud.volume_backup:
    cloud: "{{ cloud }}"
    state: present
    display_name: ansible_volume_backup
    volume: ansible_volume
  register: vol_backup

- name: Get backup info
  openstack.cloud.volume_backup_info:
    cloud: "{{ cloud }}"
    name: ansible_volume_backup
  register: backup_info

- debug: var=vol

- debug: var=vol_backup

- debug: var=backup_info

- name: Delete volume backup
  openstack.cloud.volume_backup:
    cloud: "{{ cloud }}"
    display_name: ansible_volume_backup
    state: absent

- name: Delete volume
  openstack.cloud.volume:
     cloud: "{{ cloud }}"
     state: absent
     display_name: ansible_volume
