---
- name: Create keystone role
  openstack.cloud.identity_role:
     cloud: "{{ cloud }}"
     state: present
     name: "{{ role_name }}"

- name: Delete keystone role
  openstack.cloud.identity_role:
     cloud: "{{ cloud }}"
     state: absent
     name: "{{ role_name }}"
